





TVSUM_AMBIGUOUS_TITLES = {
    'AwmHb44_ouw': {'original_title': '#1306 How to change tires for off road vehicles [Davidsfarm]', 'ambiguous_title': 'Vehicle Maintenance'},
    '98MoyGZKHXc': {'original_title': 'How to use a tyre repair kit - Which? guide', 'ambiguous_title': 'Fixing a Vehicle Part'},
    'J0nA4VgnoCo': {'original_title': '#0001: FLAT TIRE', 'ambiguous_title': 'Automotive Problem'},
    'gzDbaEs1Rlg': {'original_title': 'ŠKODA Tips How to Repair Your Tyre', 'ambiguous_title': 'Repairing a Wheel'},
    'XzYM3PfTM4w': {'original_title': 'When to Replace Your Tires GMC', 'ambiguous_title': 'Checking a Vehicle'},
    'HT5vyqe0Xaw': {'original_title': '"The stuck truck of Mark, The rut that filled an afternoon."', 'ambiguous_title': 'Vehicle Issue'},
    'sTEELN-vY30': {'original_title': 'BBC - Train crash 2013', 'ambiguous_title': 'Transportation Incident'},
    'vdmoEJ5YbrQ': {'original_title': '#453 girl gets van stuck in the back fourty [Davidsfarm]', 'ambiguous_title': 'Driving Problem'},
    'xwqBXPGE9pQ': {'original_title': 'Smart Electric Vehicle Balances on Two Wheels', 'ambiguous_title': 'A Vehicle in Motion'},
    'akI8YFjEmUw': {'original_title': 'Electric cars making earth more green', 'ambiguous_title': 'Environmental Technology'},
    'i3wAGJaaktw': {'original_title': '"Pet Joy Spa Grooming Services | Brentwood, CA (310) 471-0088"', 'ambiguous_title': 'Animal Care'},
    'Bhxk-O1Y7Ho': {'original_title': '"Vlog #509 I\'M A PUPPY DOG GROOMER! September 13, 2014"', 'ambiguous_title': 'Taking Care of a Pet'},
    '0tmA_C6XwfM': {'original_title': 'Nail clipper Gloria Pets professional grooming', 'ambiguous_title': 'Animal Grooming'},
    '3eYKfiOEJNs': {'original_title': 'Dog Grooming in Buenos Aires', 'ambiguous_title': 'Pet Services'},
    'xxdtq8mxegs': {'original_title': "How to Clean Your Dog's Ears - Vetoquinol USA", 'ambiguous_title': 'Cleaning an Animal'},
    'WG0MBPpPC6I': {'original_title': 'Mexican Fried Chicken Sandwich Recipe', 'ambiguous_title': 'Preparing a Meal'},
    'Hl-__g2gn_A': {'original_title': 'Reuben Sandwich with Corned Beef & Sauerkraut', 'ambiguous_title': 'Making Lunch'},
    'Yi4Ij2NM7U4': {'original_title': "Poor Man's Meals: Spicy Sausage Sandwich", 'ambiguous_title': 'Cooking Food'},
    '37rzWOQsNIw': {'original_title': 'Saigon Sandwich - Vietnamese Sandwiches in San Francisco CA', 'ambiguous_title': 'Food Preparation'},
    'LRw_obCPUt0': {'original_title': "GoogaMooga Sneak Peek Joseph Leonard's Fried Chicken Sandwich cooking video", 'ambiguous_title': 'Kitchen Activity'},
    'cjibtmSLxQ4': {'original_title': 'David Belle | Fondateur du parkour | Reportage de TF1', 'ambiguous_title': 'Urban Acrobatics'},
    'b626MiF1ew4': {'original_title': 'Charlotte Parkour | Charlotte Video Project', 'ambiguous_title': 'City Athletics'},
    'XkqCExn6_Us': {'original_title': 'Singapore Parkour Free Running | JC Boy Late for School', 'ambiguous_title': 'Person in Motion'},
    'GsAD1KT1xo8': {'original_title': 'Parkour Camp Leipzig', 'ambiguous_title': 'Athletic Training'},
    'PJrm840pAUI': {'original_title': 'Vivencias: Jam Parkour Viña del Mar 2012', 'ambiguous_title': 'Physical Activity'},
    '91IHQYk1IQM': {'original_title': 'Chinese New Year Parade 2012 New York City Chinatown', 'ambiguous_title': 'Street Celebration'},
    'RBCABdttQmI': {'original_title': '2013 Alumnae Parade & Laurel Chain Ceremony', 'ambiguous_title': 'Public Procession'},
    'z_6gVvQb2d0': {'original_title': 'LA Kings Stanley Cup South Bay Parade 2014', 'ambiguous_title': 'Group Event'},
    'fWutDQy1nnY': {'original_title': 'Chinatown Parade', 'ambiguous_title': 'Community Gathering'},
    '4wU_LUjG5Ic': {'original_title': 'Southend-on-Sea and Kortrijk Bike Friendly Cities Parades', 'ambiguous_title': 'Public Spectacle'},
    'VuWGsYPqAX8': {'original_title': '"Flash mob protest for Syria | Sydney, Australia, May 2012 | #Silenceisbetrayal"', 'ambiguous_title': 'Organized Gathering'},
    'JKpqYvAdIsw': {'original_title': 'ICC World Twenty20 Bangladesh 2014 Flash Mob - Pabna University of Science & Technology ( PUST )', 'ambiguous_title': 'Group Performance'},
    'xmEERLqJ2kU': {'original_title': 'Bluffton Teachers Flash Mob Dance (A Staff that Cares About Their Students)', 'ambiguous_title': 'Public Dance'},
    'byxOvuiIJV0': {'original_title': '"ICC World Twenty 20 Bangladesh 2014, Flash Mob - UITS, Chittagong (Official)"', 'ambiguous_title': 'Coordinated Event'},
    '_xMr-HKMfVA': {'original_title': 'CASACL - Flashmob in Copenhagen underground - Peer Gynt', 'ambiguous_title': 'Surprise Performance'},
    'WxtbjNsCQ8A': {'original_title': 'Beekeeping101.mov', 'ambiguous_title': 'Interacting with Insects'},
    'uGu_10sucQo': {'original_title': 'A Year of Beekeeping', 'ambiguous_title': 'Handling Wildlife'},
    'EE-bNr36nyA': {'original_title': 'Paper Wasp Removal | From the Ground Up', 'ambiguous_title': 'Outdoor Task'},
    'Se3oxnaPsz0': {'original_title': '9/15/11 Killer Bees Kill 1000-lb Hog in Bisbee AZ', 'ambiguous_title': 'Animal Interaction'},
    'oDXZc0tZe04': {'original_title': 'Apis Mellifera in a Vertical Log Hive', 'ambiguous_title': 'Observing Nature'},
    'qqR6AEXwxoQ': {'original_title': 'Motocross Tips & Tricks : How to Whip a Motocross Bike', 'ambiguous_title': 'Performing a Stunt'},
    'EYqVtI9YWJA': {'original_title': 'Smage Bros. Motorcycle Stunt Show', 'ambiguous_title': 'Vehicle Tricks'},
    'eQu1rNs0an0': {'original_title': 'How to stop your Fixie', 'ambiguous_title': 'Using a Bicycle'},
    'JgHubY5Vw3Y': {'original_title': 'How to lock your bike. The RIGHT way!', 'ambiguous_title': 'Bicycle Security'},
    'iVt07TCkFM0': {'original_title': 'Pure Fix TV: How to Wheelie', 'ambiguous_title': 'Bike Maneuvers'},
    'E11zDS9XGzg': {'original_title': 'German Shepherd Dog Show (KCI) | DoHangout', 'ambiguous_title': 'Animal Competition'},
    'NyBmCxDoHJU': {'original_title': 'The Dog Show HD 720p', 'ambiguous_title': 'Pet Event'},
    'kLxoNp-UchI': {'original_title': "Oliver's Show - Dog's tale", 'ambiguous_title': 'A Story About a Pet'},
    'jcoYJXDG9sw': {'original_title': 'TODAY- Obie the obese dog works toward weight loss', 'ambiguous_title': 'Animal Health'},
    '-esJrBWj2d8': {'original_title': 'Will A Cat Eat Dog Food?', 'ambiguous_title': 'Domestic Animals'}
}



TVSUM_UNRELATED_TITLES = {
    'AwmHb44_ouw': {'original_title': '#1306 How to change tires for off road vehicles [Davidsfarm]', 'unrelated_title': 'Beekeeping101.mov'},
    '98MoyGZKHXc': {'original_title': 'How to use a tyre repair kit - Which? guide', 'unrelated_title': 'David Belle | Fondateur du parkour | Reportage de TF1'},
    'J0nA4VgnoCo': {'original_title': '#0001: FLAT TIRE', 'unrelated_title': 'Will A Cat Eat Dog Food?'},
    'gzDbaEs1Rlg': {'original_title': 'ŠKODA Tips How to Repair Your Tyre', 'unrelated_title': 'Chinese New Year Parade 2012 New York City Chinatown'},
    'XzYM3PfTM4w': {'original_title': 'When to Replace Your Tires GMC', 'unrelated_title': 'Bluffton Teachers Flash Mob Dance (A Staff that Cares About Their Students)'},
    'HT5vyqe0Xaw': {'original_title': '"The stuck truck of Mark, The rut that filled an afternoon."', 'unrelated_title': 'Pure Fix TV: How to Wheelie'},
    'sTEELN-vY30': {'original_title': 'BBC - Train crash 2013', 'unrelated_title': '"Vlog #509 I\'M A PUPPY DOG GROOMER! September 13, 2014"'},
    'vdmoEJ5YbrQ': {'original_title': '#453 girl gets van stuck in the back fourty [Davidsfarm]', 'unrelated_title': 'Mexican Fried Chicken Sandwich Recipe'},
    'xwqBXPGE9pQ': {'original_title': 'Smart Electric Vehicle Balances on Two Wheels', 'unrelated_title': 'Southend-on-Sea and Kortrijk Bike Friendly Cities Parades'},
    'akI8YFjEmUw': {'original_title': 'Electric cars making earth more green', 'unrelated_title': 'Paper Wasp Removal | From the Ground Up'},
    'i3wAGJaaktw': {'original_title': '"Pet Joy Spa Grooming Services | Brentwood, CA (310) 471-0088"', 'unrelated_title': 'When to Replace Your Tires GMC'},
    'Bhxk-O1Y7Ho': {'original_title': '"Vlog #509 I\'M A PUPPY DOG GROOMER! September 13, 2014"', 'unrelated_title': 'GoogaMooga Sneak Peek Joseph Leonard\'s Fried Chicken Sandwich cooking video'},
    '0tmA_C6XwfM': {'original_title': 'Nail clipper Gloria Pets professional grooming', 'unrelated_title': 'Parkour Camp Leipzig'},
    '3eYKfiOEJNs': {'original_title': 'Dog Grooming in Buenos Aires', 'unrelated_title': 'How to stop your Fixie'},
    'xxdtq8mxegs': {'original_title': "How to Clean Your Dog's Ears - Vetoquinol USA", 'unrelated_title': 'BBC - Train crash 2013'},
    'WG0MBPpPC6I': {'original_title': 'Mexican Fried Chicken Sandwich Recipe', 'unrelated_title': 'German Shepherd Dog Show (KCI) | DoHangout'},
    'Hl-__g2gn_A': {'original_title': 'Reuben Sandwich with Corned Beef & Sauerkraut', 'unrelated_title': 'Smart Electric Vehicle Balances on Two Wheels'},
    'Yi4Ij2NM7U4': {'original_title': "Poor Man's Meals: Spicy Sausage Sandwich", 'unrelated_title': 'Dog Grooming in Buenos Aires'},
    '37rzWOQsNIw': {'original_title': 'Saigon Sandwich - Vietnamese Sandwiches in San Francisco CA', 'unrelated_title': 'How to lock your bike. The RIGHT way!'},
    'LRw_obCPUt0': {'original_title': "GoogaMooga Sneak Peek Joseph Leonard's Fried Chicken Sandwich cooking video", 'unrelated_title': 'Singapore Parkour Free Running | JC Boy Late for School'},
    'cjibtmSLxQ4': {'original_title': 'David Belle | Fondateur du parkour | Reportage de TF1', 'unrelated_title': 'TODAY- Obie the obese dog works toward weight loss'},
    'b626MiF1ew4': {'original_title': 'Charlotte Parkour | Charlotte Video Project', 'unrelated_title': 'CASACL - Flashmob in Copenhagen underground - Peer Gynt'},
    'XkqCExn6_Us': {'original_title': 'Singapore Parkour Free Running | JC Boy Late for School', 'unrelated_title': 'The Dog Show HD 720p'},
    'GsAD1KT1xo8': {'original_title': 'Parkour Camp Leipzig', 'unrelated_title': '"The stuck truck of Mark, The rut that filled an afternoon."'},
    'PJrm840pAUI': {'original_title': 'Vivencias: Jam Parkour Viña del Mar 2012', 'unrelated_title': 'Apis Mellifera in a Vertical Log Hive'},
    '91IHQYk1IQM': {'original_title': 'Chinese New Year Parade 2012 New York City Chinatown', 'unrelated_title': 'How to use a tyre repair kit - Which? guide'},
    'RBCABdttQmI': {'original_title': '2013 Alumnae Parade & Laurel Chain Ceremony', 'unrelated_title': '#453 girl gets van stuck in the back fourty [Davidsfarm]'},
    'z_6gVvQb2d0': {'original_title': 'LA Kings Stanley Cup South Bay Parade 2014', 'unrelated_title': 'Smage Bros. Motorcycle Stunt Show'},
    'fWutDQy1nnY': {'original_title': 'Chinatown Parade', 'unrelated_title': 'Nail clipper Gloria Pets professional grooming'},
    '4wU_LUjG5Ic': {'original_title': 'Southend-on-Sea and Kortrijk Bike Friendly Cities Parades', 'unrelated_title': 'Saigon Sandwich - Vietnamese Sandwiches in San Francisco CA'},
    'VuWGsYPqAX8': {'original_title': '"Flash mob protest for Syria | Sydney, Australia, May 2012 | #Silenceisbetrayal"', 'unrelated_title': 'Oliver\'s Show - Dog\'s tale'},
    'JKpqYvAdIsw': {'original_title': 'ICC World Twenty20 Bangladesh 2014 Flash Mob - Pabna University of Science & Technology ( PUST )', 'unrelated_title': '#0001: FLAT TIRE'},
    'xmEERLqJ2kU': {'original_title': 'Bluffton Teachers Flash Mob Dance (A Staff that Cares About Their Students)', 'unrelated_title': 'Electric cars making earth more green'},
    'byxOvuiIJV0': {'original_title': '"ICC World Twenty 20 Bangladesh 2014, Flash Mob - UITS, Chittagong (Official)"', 'unrelated_title': 'A Year of Beekeeping'},
    '_xMr-HKMfVA': {'original_title': 'CASACL - Flashmob in Copenhagen underground - Peer Gynt', 'unrelated_title': 'Reuben Sandwich with Corned Beef & Sauerkraut'},
    'WxtbjNsCQ8A': {'original_title': 'Beekeeping101.mov', 'unrelated_title': 'Chinatown Parade'},
    'uGu_10sucQo': {'original_title': 'A Year of Beekeeping', 'unrelated_title': 'LA Kings Stanley Cup South Bay Parade 2014'},
    'EE-bNr36nyA': {'original_title': 'Paper Wasp Removal | From the Ground Up', 'unrelated_title': "How to Clean Your Dog's Ears - Vetoquinol USA"},
    'Se3oxnaPsz0': {'original_title': '9/15/11 Killer Bees Kill 1000-lb Hog in Bisbee AZ', 'unrelated_title': 'Charlotte Parkour | Charlotte Video Project'},
    'oDXZc0tZe04': {'original_title': 'Apis Mellifera in a Vertical Log Hive', 'unrelated_title': 'ŠKODA Tips How to Repair Your Tyre'},
    'qqR6AEXwxoQ': {'original_title': 'Motocross Tips & Tricks : How to Whip a Motocross Bike', 'unrelated_title': '2013 Alumnae Parade & Laurel Chain Ceremony'},
    'EYqVtI9YWJA': {'original_title': 'Smage Bros. Motorcycle Stunt Show', 'unrelated_title': "Poor Man's Meals: Spicy Sausage Sandwich"},
    'eQu1rNs0an0': {'original_title': 'How to stop your Fixie', 'unrelated_title': 'ICC World Twenty20 Bangladesh 2014 Flash Mob - Pabna University of Science & Technology ( PUST )'},
    'JgHubY5Vw3Y': {'original_title': 'How to lock your bike. The RIGHT way!', 'unrelated_title': '"Pet Joy Spa Grooming Services | Brentwood, CA (310) 471-0088"'},
    'iVt07TCkFM0': {'original_title': 'Pure Fix TV: How to Wheelie', 'unrelated_title': 'Vivencias: Jam Parkour Viña del Mar 2012'},
    'E11zDS9XGzg': {'original_title': 'German Shepherd Dog Show (KCI) | DoHangout', 'unrelated_title': '#1306 How to change tires for off road vehicles [Davidsfarm]'},
    'NyBmCxDoHJU': {'original_title': 'The Dog Show HD 720p', 'unrelated_title': '"Flash mob protest for Syria | Sydney, Australia, May 2012 | #Silenceisbetrayal"'},
    'kLxoNp-UchI': {'original_title': "Oliver's Show - Dog's tale", 'unrelated_title': '9/15/11 Killer Bees Kill 1000-lb Hog in Bisbee AZ'},
    'jcoYJXDG9sw': {'original_title': 'TODAY- Obie the obese dog works toward weight loss', 'unrelated_title': 'Motocross Tips & Tricks : How to Whip a Motocross Bike'},
    '-esJrBWj2d8': {'original_title': 'Will A Cat Eat Dog Food?', 'unrelated_title': '"ICC World Twenty 20 Bangladesh 2014, Flash Mob - UITS, Chittagong (Official)"'}
}